# Curated registry for RedTrip P0 (aligned with ShangHaiKaiFang slc_endpoints.py).
# Source: Shanghai Library open-data webapi / MCP package.

# 多数据源接入注册表（方案 §3 整表 28 家）随 endpoints 一并暴露。
from .providers import (  # noqa: E402,F401
    PROVIDERS,
    ProviderSpec,
    gather_partner_evidence,
    health_probe,
    list_providers,
    normalize_record,
)

ENDPOINTS = [
    {
        "id": "route_getEventList",
        "method": "GET",
        "path": "https://data1.library.sh.cn/webapi/hsly/route/getEventList",
        "params": ["eventdate", "eventfreetext"],
        "path_params": [],
        "family": "红色旅游事件",
        "needs_key": True,
    },
    {
        "id": "route_getEventDetail",
        "method": "GET",
        "path": "https://data1.library.sh.cn/webapi/hsly/route/getEventDetail",
        "params": ["uri"],
        "path_params": [],
        "family": "红色旅游事件",
        "needs_key": True,
    },
    {
        "id": "building_list",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/list",
        "params": ["freetext"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "event_list",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/event/list",
        "params": ["buri"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "building_detail",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/detail",
        "params": ["uri"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "road_list",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/road/list",
        "params": ["freetext"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "road_detail",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/road/detail",
        "params": ["uri"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "persons_list",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/list",
        "params": ["pname"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "persons_detail",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/detail",
        "params": ["uri"],
        "path_params": [],
        "family": "武康路历史",
        "needs_key": True,
    },
    {
        "id": "geonames_list",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/list",
        "params": ["freetext", "type"],
        "path_params": [],
        "family": "地名志",
        "needs_key": True,
    },
    {
        "id": "geonames_detail",
        "method": "GET",
        "path": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/detail",
        "params": ["uri"],
        "path_params": [],
        "family": "地名志",
        "needs_key": True,
    },
]
