"""红鸢词库：只影响读法，不提供新史实。

条目可按 tone_tags / companion_tags / duration_tags 过滤。
空 tags = 通用。
"""
from __future__ import annotations

from typing import TypedDict


class Entry(TypedDict, total=False):
    id: str
    label: str
    hint: str
    tone_tags: list[str]  # 文艺 / 轻社交 / 硬核
    companion_tags: list[str]  # 独自 / 2人 / 3–4人
    duration_tags: list[str]  # 30 / 60 / 90


def _e(
    id_: str,
    label: str,
    hint: str,
    *,
    tones: list[str] | None = None,
    companions: list[str] | None = None,
    durations: list[str] | None = None,
) -> Entry:
    e: Entry = {"id": id_, "label": label, "hint": hint}
    if tones:
        e["tone_tags"] = tones
    if companions:
        e["companion_tags"] = companions
    if durations:
        e["duration_tags"] = durations
    return e


# —— 情绪（约 80）——
EMOTIONS: list[Entry] = [
    _e("emo_quiet", "静默", "少惊叹，多停顿"),
    _e("emo_warm", "温热", "像傍晚路灯刚亮", tones=["轻社交", "文艺"]),
    _e("emo_cool", "清冷", "克制、不煽情", tones=["文艺", "硬核"]),
    _e("emo_wistful", "怅然", "轻轻回头，不哀嚎", tones=["文艺"]),
    _e("emo_curious", "好奇", "像翻开未读页", tones=["轻社交", "文艺"]),
    _e("emo_steady", "沉稳", "步伐均匀", tones=["硬核", "轻社交"]),
    _e("emo_tender", "柔软", "对旧物轻声", tones=["文艺", "轻社交"]),
    _e("emo_alert", "警醒", "对细节保持清醒", tones=["硬核"]),
    _e("emo_playful", "俏皮", "一点机锋，不油滑", tones=["轻社交"]),
    _e("emo_solemn", "肃然", "短句、低声", tones=["硬核", "文艺"]),
    _e("emo_distant", "疏离", "旁观式贴近", tones=["文艺"]),
    _e("emo_intimate", "贴身", "几乎耳语", tones=["文艺"], companions=["独自", "2人"]),
    _e("emo_companionable", "并肩", "可对旁人轻声转述", tones=["轻社交"], companions=["2人", "3–4人"]),
    _e("emo_resolute", "决意", "像下定决心走路", tones=["硬核"]),
    _e("emo_haze", "薄雾", "轮廓先于结论", tones=["文艺"]),
    _e("emo_bright", "明亮", "但不刺眼", tones=["轻社交"]),
    _e("emo_bittersweet", "微苦", "甜在后味", tones=["文艺"]),
    _e("emo_patient", "耐心", "允许慢读", durations=["60", "90"]),
    _e("emo_urgent", "急切", "信息更密", durations=["30", "60"], tones=["硬核", "轻社交"]),
    _e("emo_nostalgic", "怀旧", "不滥情", tones=["文艺", "轻社交"]),
    _e("emo_lucid", "澄明", "一句说清处境", tones=["硬核"]),
    _e("emo_guarded", "含蓄", "半句留给沉默", tones=["文艺"]),
    _e("emo_open", "敞开", "愿意分享发现", tones=["轻社交"]),
    _e("emo_grave", "沉重", "压低音量", tones=["硬核"]),
    _e("emo_light", "轻盈", "脚步不粘地", tones=["轻社交"]),
    _e("emo_focused", "专注", "视线钉在一处细节", tones=["硬核", "文艺"]),
    _e("emo_drifting", "游移", "允许思绪旁逸", tones=["文艺"], durations=["90"]),
    _e("emo_grounded", "落地", "脚感先于概念", tones=["轻社交", "硬核"]),
    _e("emo_reverent", "敬意", "对出处保持礼貌", tones=["硬核", "文艺"]),
    _e("emo_skeptical", "审慎", "先问出处再感动", tones=["硬核"]),
    _e("emo_hopeful", "微光", "不夸张的希望", tones=["轻社交", "文艺"]),
    _e("emo_melancholy", "淡愁", "像旧信折痕", tones=["文艺"]),
    _e("emo_calm", "安宁", "呼吸放慢", tones=["文艺", "轻社交"]),
    _e("emo_intense", "凝注", "短时高密度", durations=["30"], tones=["硬核"]),
    _e("emo_gentle", "和缓", "不推人走太快", tones=["轻社交", "文艺"]),
    _e("emo_dry", "干爽", "少形容词", tones=["硬核"]),
    _e("emo_lush", "丰润", "感官略多一点", tones=["文艺"]),
    _e("emo_spare", "简净", "留白大于修辞", tones=["文艺", "硬核"]),
    _e("emo_echo", "回声", "句子可重复一拍", tones=["文艺"]),
    _e("emo_present", "当下", "强调此刻站位", tones=["轻社交"]),
    _e("emo_layered", "层叠", "情绪有前后景", tones=["文艺"], durations=["90"]),
    _e("emo_plain", "素面", "不化妆的句子", tones=["硬核", "轻社交"]),
    _e("emo_ink", "墨意", "晕开而不糊", tones=["文艺"]),
    _e("emo_steel", "铁青", "硬、直、短", tones=["硬核"]),
    _e("emo_tea", "茶意", "回甘型收束", tones=["文艺", "轻社交"]),
    _e("emo_rain", "微雨", "潮湿但不凄厉", tones=["文艺"]),
    _e("emo_sunlit", "晒痕", "有温度的旧物感", tones=["轻社交", "文艺"]),
    _e("emo_night", "夜色", "低光叙述", tones=["文艺"]),
    _e("emo_dawn", "晨意", "刚醒的城市", tones=["轻社交"]),
    _e("emo_autumn", "秋意", "收、敛、清", tones=["文艺"]),
    _e("emo_spring", "春讯", "轻、新、可分享", tones=["轻社交"]),
    _e("emo_winter", "冬骨", "干净的硬", tones=["硬核", "文艺"]),
    _e("emo_summer", "夏荫", "慢、荫、可停", tones=["轻社交"], durations=["90"]),
    _e("emo_threshold", "门槛", "站在进与不进之间", tones=["文艺", "硬核"]),
    _e("emo_archive", "档案气", "冷静翻页", tones=["硬核"]),
    _e("emo_letter", "信笺气", "像写给一个人", tones=["文艺"], companions=["独自", "2人"]),
    _e("emo_street", "街声", "混着脚步与闲话", tones=["轻社交"]),
    _e("emo_courtyard", "院落", "向内收", tones=["文艺"]),
    _e("emo_balcony", "阳台", "半私密半城市", tones=["文艺", "轻社交"]),
    _e("emo_corridor", "走廊", "过渡中的清醒", tones=["硬核", "文艺"]),
    _e("emo_doorway", "门洞", "一进一出的张力", tones=["文艺", "硬核"]),
    _e("emo_window", "窗边", "内外对照", tones=["文艺"]),
    _e("emo_bridge", "桥上", "两岸对看", tones=["文艺", "轻社交"]),
    _e("emo_map", "图上", "像用手指描线", tones=["轻社交", "硬核"]),
    _e("emo_pocket", "口袋", "把细节装走", tones=["轻社交"]),
    _e("emo_shadow", "影子", "人在光边", tones=["文艺"]),
    _e("emo_dust", "微尘", "时间落在物上", tones=["文艺", "硬核"]),
    _e("emo_stone", "石意", "沉、稳、可触", tones=["硬核"]),
    _e("emo_paper", "纸感", "翻页的轻响", tones=["文艺"]),
    _e("emo_voice", "嗓音", "像有人低声指路", tones=["轻社交"]),
    _e("emo_silence", "无声", "用空白当标点", tones=["文艺", "硬核"]),
    _e("emo_pulse", "脉搏", "句子有心跳间隔", tones=["文艺"]),
    _e("emo_compass", "罗盘", "始终回线索", tones=["硬核", "轻社交"]),
    _e("emo_lantern", "灯笼", "一小团暖光", tones=["轻社交", "文艺"]),
    _e("emo_inkstone", "砚台", "沉、墨、慢磨", tones=["文艺", "硬核"]),
    _e("emo_kite", "鸢影", "高一点看整条线", tones=["文艺", "轻社交"]),
    _e("emo_root", "根须", "往下找来历", tones=["硬核"]),
    _e("emo_ripple", "涟漪", "一圈圈扩开", tones=["文艺"]),
    _e("emo_grain", "纹理", "贴近表面细看", tones=["硬核", "文艺"]),
    _e("emo_horizon", "天际", "收束时抬眼", tones=["文艺"], durations=["90"]),
    _e("emo_footfall", "足音", "一步一事", tones=["轻社交", "硬核"]),
]

# —— 说话风格（约 70）——
VOICE_STYLES: list[Entry] = [
    _e("vs_second_close", "贴耳第二人称", "「你」靠得很近", companions=["独自", "2人"]),
    _e("vs_second_walk", "并肩第二人称", "「你」像同行", companions=["2人", "3–4人"], tones=["轻社交"]),
    _e("vs_curator", "策展人低语", "说明为何选点，不导游"),
    _e("vs_archivist", "档案员口吻", "先出处后感受", tones=["硬核"]),
    _e("vs_letter", "书信体", "像写给远人", tones=["文艺"]),
    _e("vs_postcard", "明信片体", "短、可寄出", tones=["文艺", "轻社交"]),
    _e("vs_fieldnote", "田野笔记", "观察句多于评价", tones=["硬核", "文艺"]),
    _e("vs_whisper", "耳语体", "句短、声低", tones=["文艺"]),
    _e("vs_plain", "白话体", "大白话说清楚", tones=["轻社交", "硬核"]),
    _e("vs_essay", "短章体", "一段一意", tones=["文艺"]),
    _e("vs_dialogue_ready", "可转述体", "方便说给同伴听", companions=["2人", "3–4人"], tones=["轻社交"]),
    _e("vs_sparse", "疏句体", "多句号少逗号", tones=["文艺", "硬核"]),
    _e("vs_dense", "密句体", "信息更挤", tones=["硬核"], durations=["30", "60"]),
    _e("vs_oral", "口述体", "像现场说", tones=["轻社交"]),
    _e("vs_classical_light", "浅文言气", "一点点文言香，不酸", tones=["文艺"]),
    _e("vs_report", "纪要体", "条目清晰", tones=["硬核"]),
    _e("vs_scene", "场景体", "先看见再解释"),
    _e("vs_question", "问句牵引", "用问题带你走", tones=["轻社交", "文艺"]),
    _e("vs_imperative_soft", "轻祈使", "「停一下」「看这行」", tones=["轻社交"]),
    _e("vs_neutral", "中性叙述", "少情绪词", tones=["硬核"]),
    _e("vs_warm_host", "温和东道", "不谄媚的接待感", tones=["轻社交"]),
    _e("vs_shadow_guide", "影子向导", "只点一下就退开", tones=["文艺"]),
    _e("vs_map_reader", "读图人", "像对照一张看不见的图", tones=["硬核", "轻社交"]),
    _e("vs_timekeeper", "计时人", "偶尔点明节奏", durations=["30", "60"]),
    _e("vs_linger", "逗留人", "鼓励多停一会", durations=["90"], tones=["文艺", "轻社交"]),
    _e("vs_contrast", "对照口吻", "今昔并置时语气干净"),
    _e("vs_evidence_first", "证据前置", "先说记载再抒情", tones=["硬核"]),
    _e("vs_feeling_after", "感受后置", "事实走完才叹一口气", tones=["文艺", "硬核"]),
    _e("vs_minimal", "极简口吻", "删到只剩必要", tones=["硬核", "文艺"]),
    _e("vs_textured", "质感口吻", "允许一个感官细节", tones=["文艺"]),
    _e("vs_streetwise", "街巷口吻", "接地、不端着", tones=["轻社交"]),
    _e("vs_salon", "客厅口吻", "谈得慢一点", tones=["文艺"], companions=["2人", "3–4人"]),
    _e("vs_solo_diary", "独行日记", "内心旁白", companions=["独自"], tones=["文艺"]),
    _e("vs_pair_murmur", "二人嘀咕", "像交换发现", companions=["2人"], tones=["轻社交", "文艺"]),
    _e("vs_group_pass", "小队传话", "一句能传开", companions=["3–4人"], tones=["轻社交"]),
    _e("vs_inkbrush", "墨笔口吻", "笔画有粗细", tones=["文艺"]),
    _e("vs_typewriter", "打字机口吻", "节奏笃笃", tones=["硬核", "文艺"]),
    _e("vs_radio", "旧电台", "清晰播报感，但不口号", tones=["硬核", "轻社交"]),
    _e("vs_stage_whisper", "舞台侧语", "对观众轻声", tones=["文艺"]),
    _e("vs_catalog_anti", "反目录体", "绝不报流水账"),
    _e("vs_name_first", "名字优先", "先叫人，再叫楼", tones=["文艺", "硬核"]),
    _e("vs_place_first", "地标优先", "先站稳再讲人", tones=["轻社交"]),
    _e("vs_year_click", "年份落子", "年份像棋子轻轻放下", tones=["硬核", "文艺"]),
    _e("vs_claim_echo", "原句回声", "可轻轻回扣 claim 措辞", tones=["硬核"]),
    _e("vs_soft_break", "软折行", "段落短、好喘", tones=["文艺", "轻社交"]),
    _e("vs_hard_break", "硬折行", "一句一行的力度", tones=["硬核"]),
    _e("vs_circular", "回环体", "收束时回到开篇词", tones=["文艺"], durations=["90"]),
    _e("vs_arrow", "箭头体", "始终指向下一站理由", tones=["硬核", "轻社交"]),
    _e("vs_pocket_essay", "口袋随笔", "可装进手机备忘", tones=["轻社交"]),
    _e("vs_museum_card", "展签体", "短而准", tones=["硬核"]),
    _e("vs_nightwalk", "夜行体", "光少、句慢", tones=["文艺"]),
    _e("vs_morning", "晨走体", "清、醒、利落", tones=["轻社交"]),
    _e("vs_rainwalk", "雨行体", "声音贴地面", tones=["文艺"]),
    _e("vs_courtyard", "里弄体", "转弯多、发现碎", tones=["轻社交", "文艺"]),
    _e("vs_balcony", "阳台体", "半公开的私语", tones=["文艺"]),
    _e("vs_threshold", "门槛体", "进出之间措辞谨慎", tones=["硬核", "文艺"]),
    _e("vs_bridge", "桥体", "两边对照的句法", tones=["文艺"]),
    _e("vs_ledger", "账本体", "条目清楚不冰冷", tones=["硬核"]),
    _e("vs_sketch", "速写体", "几笔勾轮廓", durations=["30"], tones=["轻社交", "文艺"]),
    _e("vs_longtake", "长镜头", "允许一段跟拍", durations=["90"], tones=["文艺"]),
    _e("vs_cut", "剪辑体", "硬切场景", tones=["硬核", "轻社交"]),
    _e("vs_dissolve", "叠化体", "今昔叠一层", tones=["文艺"]),
    _e("vs_voiceover", "旁白体", "简洁的解说感", tones=["轻社交", "硬核"]),
    _e("vs_aside", "旁白插入", "括号感的补充，但不真用括号滥堆"),
    _e("vs_measure", "尺规体", "分寸感强", tones=["硬核"]),
    _e("vs_handwarm", "手温体", "句子里有体温", tones=["轻社交", "文艺"]),
    _e("vs_kite", "红鸢体", "偶尔抬高一层总览，再落下", tones=["文艺", "轻社交"]),
    _e("vs_root", "寻根体", "往记载深处问一句", tones=["硬核"]),
    _e("vs_clean", "净口", "禁用华丽堆砌"),
]

# —— 叙事方式（约 60）——
NARRATIVES: list[Entry] = [
    _e("nar_person_spine", "人物脊柱", "整条线由人名串起"),
    _e("nar_conflict_time", "冲突随时间", "同一地点的张力前后对照"),
    _e("nar_age_mirror", "年龄对照镜", "强化 age_parallel 的今昔"),
    _e("nar_door_by_door", "挨门挨户", "一站一扇门"),
    _e("nar_thread", "细线牵引", "开篇丢线，收束拾起"),
    _e("nar_reveal", "迟点揭露", "关键名字稍后给出", tones=["文艺"]),
    _e("nar_frontload", "先亮线索", "开篇就点明为何这些点", tones=["硬核", "轻社交"]),
    _e("nar_scene_beat", "场景节拍", "每站一个可见动作"),
    _e("nar_claim_orbit", "围着 claim 转", "不离开已取证句子"),
    _e("nar_dual_life", "双重人生", "建筑层与人物层交错"),
    _e("nar_three_glances", "三次注视", "物、人、年各看一眼"),
    _e("nar_question_chain", "问题链", "每站一个小问", tones=["轻社交", "文艺"]),
    _e("nar_name_echo", "名字回声", "人名在站间复现"),
    _e("nar_year_ladder", "年份梯子", "时间感递进", tones=["硬核", "文艺"]),
    _e("nar_spatial_turn", "空间转弯", "用站位变化推情节", tones=["轻社交"]),
    _e("nar_intimate_zoom", "特写推进", "从远景到一个细节", tones=["文艺"]),
    _e("nar_wide_then_near", "先远后近", "总览→贴身", tones=["文艺", "轻社交"]),
    _e("nar_near_then_wide", "先近后远", "细节→整条线意义", tones=["硬核", "文艺"]),
    _e("nar_letter_chapters", "信笺分章", "每站像一页信", tones=["文艺"]),
    _e("nar_exhibit_rooms", "展厅递进", "像走进相连展室", tones=["硬核", "轻社交"]),
    _e("nar_rehearsal", "预演收束", "中途暗示结尾将带走的名字", durations=["90"]),
    _e("nar_sprint", "短跑", "钩子密、过渡快", durations=["30"]),
    _e("nar_stroll", "散步", "过渡可稍慢", durations=["90"], tones=["轻社交", "文艺"]),
    _e("nar_contrast_pair", "成对对照", "相邻两站互相解释"),
    _e("nar_solo_interior", "内独白", "外景少、内心准", companions=["独自"], tones=["文艺"]),
    _e("nar_shared_notice", "共同发现", "适合两人交换看法", companions=["2人"], tones=["轻社交"]),
    _e("nar_pass_along", "传递发现", "一句能传给小队", companions=["3–4人"], tones=["轻社交"]),
    _e("nar_threshold_drama", "门槛戏剧", "进出、可见/不可见", tones=["文艺", "硬核"]),
    _e("nar_archive_walk", "档案散步", "边走边翻看不见的册页", tones=["硬核"]),
    _e("nar_map_unfold", "地图展开", "点位像依次按亮", tones=["轻社交"]),
    _e("nar_echo_ending", "回声结尾", "收束句呼应开篇"),
    _e("nar_open_ending", "微开结尾", "留下一个可继续的问题", tones=["文艺"]),
    _e("nar_closed_gift", "礼物结尾", "明确带走一个名字", tones=["轻社交", "硬核"]),
    _e("nar_layer_peel", "剥层", "building→event→person"),
    _e("nar_layer_stack", "叠层", "同时听见多层身份"),
    _e("nar_silence_beat", "静音拍", "允许一处不解释的停顿", tones=["文艺"]),
    _e("nar_evidence_ladder", "证据阶梯", "每站加一口出处重量", tones=["硬核"]),
    _e("nar_mood_weather", "气氛如天气", "情绪贯穿但不盖过事实", tones=["文艺"]),
    _e("nar_object_focus", "物件锚点", "若 claim 有物就盯住它"),
    _e("nar_address_focus", "地址锚点", "站稳门牌再讲人"),
    _e("nar_role_cast", "角色分工", "突出不同人的处境角色"),
    _e("nar_time_slip", "轻时间滑动", "今昔对照，不穿越胡说", tones=["文艺"]),
    _e("nar_present_tense", "现在进行", "锚定当下在场感，叙述站稳此时此地"),
    _e("nar_past_weight", "过去压来", "记载像潮水碰到脚", tones=["文艺", "硬核"]),
    _e("nar_micro_conflict", "微冲突", "目标与阻碍只取 claim 内有的"),
    _e("nar_care_work", "照看与生计", "若 claim 有照看/生计就推前", tones=["文艺", "硬核"]),
    _e("nar_creation", "创作现场", "若 claim 有创作就推前", tones=["文艺"]),
    _e("nar_residence", "居住现场", "迁入/定居类 claim 推前"),
    _e("nar_public_private", "公私交界", "阳台、门、窗的张力", tones=["文艺"]),
    _e("nar_route_as_sentence", "路线如句", "站=词，衔接=语法"),
    _e("nar_collecting", "采集", "沉淀一句可核对的事实，留待带走", tones=["硬核", "轻社交"]),
    _e("nar_witness", "见证", "以见证者视角沉淀此刻，不指称读者", tones=["文艺", "硬核"]),
    _e("nar_apprentice", "学徒", "跟着记载学看一座城", tones=["轻社交"]),
    _e("nar_hunter", "寻线人", "跟着人名追下一站", tones=["硬核", "轻社交"]),
    _e("nar_reader", "读者入城", "把街道当书页", tones=["文艺"]),
    _e("nar_guest", "客人", "有分寸的拜访感", tones=["轻社交", "文艺"]),
    _e("nar_return", "重返", "像第二次来，更懂看什么", tones=["文艺"], durations=["90"]),
    _e("nar_first_time", "初遇", "允许一点点生疏", tones=["轻社交"]),
    _e("nar_kite_overview", "红鸢俯视", "中段抬高看整条人物线再落下", tones=["文艺", "轻社交"]),
]

# —— 知识延伸角度（约 50）—— 只能是「读法角度」，禁止当新事实输出
KNOWLEDGE_ANGLES: list[Entry] = [
    _e("know_source_habit", "出处习惯", "提醒读者养成先看来源的习惯"),
    _e("know_name_relation", "人名关系", "把注意力放在人名如何互指"),
    _e("know_year_sense", "年代感", "年份如何改变读同一栋楼的方式"),
    _e("know_address_read", "地址阅读", "门牌/路名如何参与叙事"),
    _e("know_layer_literacy", "层识字", "教人分辨 building/event/person 层"),
    _e("know_gap_honesty", "空隙诚实", "未收录处如何诚实停住"),
    _e("know_age_bridge", "年龄桥", "用年龄对照连接今人与记载"),
    _e("know_urban_form", "城市形态", "里弄/别墅/阳台作为空间语法", tones=["文艺", "轻社交"]),
    _e("know_work_life", "生计与居住", "当 claim 涉及生计时放大读", tones=["硬核", "文艺"]),
    _e("know_care", "照看伦理", "照看、迁入等动词的重量", tones=["文艺"]),
    _e("know_creation", "创作现场感", "作品与地点的可核对关系", tones=["文艺"]),
    _e("know_public_memory", "公共记忆", "个人名字如何进入可共享叙述", tones=["轻社交", "硬核"]),
    _e("know_private_threshold", "私密门槛", "可看与不可进的边界", tones=["文艺", "硬核"]),
    _e("know_compare_stops", "站间比较", "教人拿两站互相解释"),
    _e("know_anti_checklist", "反打卡清单", "反对把路线读成任务表"),
    _e("know_quote_discipline", "引述纪律", "不改写 claim 里的硬信息"),
    _e("know_silence_info", "沉默也是信息", "缺层时不编造补齐", tones=["硬核", "文艺"]),
    _e("know_map_literacy", "地图识读", "坐标可信与示意高度的区别", tones=["硬核", "轻社交"]),
    _e("know_time_budget", "时间预算", "短时如何只抓主线索", durations=["30", "60"]),
    _e("know_linger_value", "逗留价值", "长时如何多读一层", durations=["90"]),
    _e("know_share_phrase", "可分享短句", "产出一句能转述且可核对的话", tones=["轻社交"]),
    _e("know_solo_attention", "独行注意力", "独自时如何更贴细节", companions=["独自"]),
    _e("know_pair_dialogue", "二人对谈点", "给两人一个可讨论的对照", companions=["2人"]),
    _e("know_group_relay", "小队接力", "让不同人各自盯一层", companions=["3–4人"]),
    _e("know_material_trace", "物证痕迹", "若有物就追问它如何进入记载"),
    _e("know_verb_watch", "动词观察", "迁入/创作/照看等动词"),
    _e("know_role_watch", "角色观察", "房主/居住者/被记载者"),
    _e("know_scale_shift", "尺度切换", "人—楼—路 三层缩放"),
    _e("know_continuity", "连续性", "为何不是散点而是一条线"),
    _e("know_rupture", "断裂处", "记载中断时如何措辞", tones=["硬核", "文艺"]),
    _e("know_courtesy", "拜访礼貌", "对仍在使用空间的克制", tones=["轻社交", "文艺"]),
    _e("know_photo_ethics", "拍摄克制", "不鼓励打扰式打卡", tones=["轻社交"]),
    _e("know_reading_aloud", "轻声读出", "把 claim 当可听的一句", tones=["轻社交", "文艺"]),
    _e("know_note_taking", "笔记法", "建议记下可回查的字段感（不造字段名堆砌）", tones=["硬核"]),
    _e("know_theme_question", "主题提问", "每站回到一个主题问"),
    _e("know_cast_board", "人物表意识", "开篇建立名字清单感"),
    _e("know_exit_gift", "离场礼物", "结束时确认带走的名字"),
    _e("know_revisit", "重访理由", "为什么值得再来", durations=["90"], tones=["文艺"]),
    _e("know_first_filter", "初访过滤", "第一次只抓主线", durations=["30", "60"]),
    _e("know_soundscape", "声景角度", "用脚步/街声衬托，不编造历史音", tones=["文艺", "轻社交"]),
    _e("know_lightscape", "光影角度", "用当下光线作舞台，不伪称当年光", tones=["文艺"]),
    _e("know_texture", "材质角度", "墙/门/窗的可观察质感", tones=["文艺", "硬核"]),
    _e("know_boundary", "边界角度", "围墙、门禁、示意高度的诚实", tones=["硬核"]),
    _e("know_network", "关系网角度", "名字如何织成网", tones=["硬核", "文艺"]),
    _e("know_ordinary", "日常角度", "伟大叙事之外的生活记载", tones=["轻社交", "文艺"]),
    _e("know_crisis", "压力时刻", "若 claim 含冲突就读压力", tones=["硬核"]),
    _e("know_care_network", "照看网络", "人与人如何被记载为互相牵连", tones=["文艺"]),
    _e("know_city_modern", "城市现代性", "只作读法透镜，不另加史实", tones=["文艺", "硬核"]),
    _e("know_hai_pai", "海派阅读", "克制、具体、去神剧", tones=["文艺", "轻社交"]),
    _e("know_kite_meta", "红鸢视角", "提醒：读法可变，出处不可变"),
]

# —— 节奏（约 40）——
PACINGS: list[Entry] = [
    _e("pace_allegro", "快板", "钩子密、过渡短", durations=["30", "60"]),
    _e("pace_moderato", "中板", "均匀推进"),
    _e("pace_adagio", "慢板", "允许逗留", durations=["90"], tones=["文艺", "轻社交"]),
    _e("pace_staccato", "断奏", "短句切开", tones=["硬核", "文艺"]),
    _e("pace_legato", "连奏", "站间气口相连", tones=["文艺"]),
    _e("pace_pulse", "脉搏式", "紧张—松一口气循环"),
    _e("pace_wave", "波浪式", "密—疏—密", durations=["60", "90"]),
    _e("pace_arrow", "箭式", "全程指向收束带走的名字"),
    _e("pace_spiral", "螺旋", "同一主题越转越近", tones=["文艺"]),
    _e("pace_ladder", "阶梯", "信息密度逐步升高", tones=["硬核"]),
    _e("pace_breath", "呼吸式", "每站末留半拍", tones=["文艺", "轻社交"]),
    _e("pace_cut", "硬切", "少铺垫", durations=["30"], tones=["硬核", "轻社交"]),
    _e("pace_fade", "淡入淡出", "开篇缓、收束缓", durations=["90"]),
    _e("pace_spotlight", "追光", "每站只照亮一个焦点"),
    _e("pace_wide_shot", "远景插入", "中段抬高看全线", tones=["文艺", "轻社交"]),
    _e("pace_closeup", "特写串烧", "细节接力", tones=["文艺", "硬核"]),
    _e("pace_duo", "对位", "两站一组对读", companions=["2人", "3–4人"]),
    _e("pace_solo", "独行拍", "更内收的时间感", companions=["独自"]),
    _e("pace_relay", "接力拍", "适合小队轮流注意", companions=["3–4人"], tones=["轻社交"]),
    _e("pace_tight", "收束紧", "结尾干净利落", durations=["30", "60"]),
    _e("pace_linger_end", "尾声留白", "结束后仍在回味", durations=["90"], tones=["文艺"]),
    _e("pace_front_heavy", "前重", "开篇信息足", tones=["硬核", "轻社交"]),
    _e("pace_back_heavy", "后重", "意义在后半显影", tones=["文艺"]),
    _e("pace_even", "均匀秤", "每站分量接近"),
    _e("pace_peak_mid", "中段峰", "中间站最用力", durations=["60", "90"]),
    _e("pace_quiet_mid", "中段静", "中间突然更安静", tones=["文艺"]),
    _e("pace_march", "行进", "步伐感强", tones=["硬核", "轻社交"]),
    _e("pace_drift", "游走", "允许轻微旁逸后拉回", tones=["文艺"]),
    _e("pace_check", "核对节拍", "每站点一次出处", tones=["硬核"]),
    _e("pace_share", "分享节拍", "每站给一句可转述", tones=["轻社交"]),
    _e("pace_ink", "墨晕节拍", "意思慢慢渗开", tones=["文艺"]),
    _e("pace_stone", "落石节拍", "关键句沉重短促", tones=["硬核"]),
    _e("pace_tea", "茶序", "温—浓—回甘", tones=["文艺", "轻社交"]),
    _e("pace_train", "站站停", "到站开门、离站关门"),
    _e("pace_film", "胶片格", "一站一帧", tones=["文艺"]),
    _e("pace_radio", "电台段", "段与段切换清晰", tones=["轻社交", "硬核"]),
    _e("pace_garden", "园径", "绕一点再见到主景", tones=["文艺"], durations=["90"]),
    _e("pace_alley", "弄堂折返", "小转折多", tones=["轻社交", "文艺"]),
    _e("pace_bridge", "过桥", "中段完成一次对照跨越"),
    _e("pace_kite", "放鸢", "先放高再收线到一个名字"),
]

LEXICON: dict[str, list[Entry]] = {
    "emotion": EMOTIONS,
    "voice_style": VOICE_STYLES,
    "narrative": NARRATIVES,
    "knowledge_angle": KNOWLEDGE_ANGLES,
    "pacing": PACINGS,
}


def lexicon_stats() -> dict[str, int]:
    return {k: len(v) for k, v in LEXICON.items()}
